replicaCount: 1
image:
  repository: acrfinalprojectrafa.azurecr.io/backend
  tag: 0.0.2-SNAPSHOT
imagePullSecret: acr-secret
env:
  dbHost: 10.0.1.5
  dbPort: "5432"
  dbName: mydb
  dbUser: postgres
  secretName: db-secret
  secretKey: password
resources:
  requests:
    memory: "500Mi"
    cpu: "200m"
  limits:
    memory: "750Mi"
    cpu: "600m"
